language: ruby
rvm:
  - 2.6.5
install: bundle install
services:
  - postgresql
  - xvfb
install:
  - bundle install --jobs 3 --retry 3
  - nvm install 12
  - npm i -g yarn
  - yarn
script:
  - bundle exec rake db:migrate:reset RAILS_ENV=test
  - bundle exec rspec